### ISSUE TITLE
question about the parameters of model

### ISSUE THREAD

**Issue by PhucHau0312** [puar-playground/LACE#3]
Hi, congratulations on your experiment!
After running train.py, what do the params "sample_t_max", "num_timesteps" and "ddim_num_steps" mean ?  They are not the same, right ?

**Comment by puar-playground** [comment]
sample_t_max is just a convenient flag used in training, which controls the range of time steps sampled for training. num_timesteps is the time steps used in the DDPM model (training). ddim_num_steps is the number of steps used for DDIM sampling (testing).
