### ISSUE TITLE
LayoutNet need training?

### ISSUE THREAD

**Issue by csf0429** [puar-playground/LACE#4]
I want to use fid as metric for evaluation. If I should train a layoutnet to compute the fid ?

**Comment by puar-playground** [comment]
No, you don't need to train a model. The fid model is adopted from previous paper and is available here:
`wget https://huggingface.co/datasets/puar-playground/LACE/resolve/main/fid.tar.gz`
The test.py script will use these checkpoints to compute FID scores.

**Comment by csf0429** [comment]
@puar-playground thank you for your reply. Could you tell me whether these model is only work on some specific dataset? Such as Rico. If I want to evaluate the performance of my model on a new dataset, Can these pretrained model also work well?

**Comment by puar-playground** [comment]
The dowloaded zip file contains 3 checkpoint for rico25-max25, rico25-max13, PubLayNet. 

If you want to test on a new model. You should use the "train_fid_model.py" script to train a new FIDnet.
